### PR TITLE
界面友好化

### PR DESCRIPTION
**Pull request by lightsing**

### CODE REVIEW

**Comment by ProfFan** [comment]
Have you really added all your source code into the commit? See https://github.com/SUSTC/PhysicsExprSimulationTest/pull/1/files

**Comment by lightsing** [comment]
Yes?

**Comment by ProfFan** [comment]
I did not see any changes except changes on file permissions.

**Comment by lightsing** [comment]
You can merge it now

**Comment by ProfFan** [comment]
比较敏感的东西还是不要放自己的网站了，没必要缓存的 :>

**Comment by lightsing** [comment]
```
        额，减少对服务器的访问可以隐蔽些吧
```

**Comment by ProfFan** [comment]
前段时间尔雅课题库的作者被喝茶了

**Comment by ProfFan** [comment]
更新可以用GitHub的raw访问和Release实现，不需要独立服务器

**Comment by lightsing** [comment]
```
        下一版做吧
```

**Comment by lightsing** [comment]
```
        而且用的是github pages做的更新，不是我的服务器
```

**Pull request merged**
